[project]
name = "fly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "erakoto", email = "enotahiana@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "pydantic>=2.13.5",
    "webcolors>=25.10.0"
]

[project.scripts]
fly = "fly:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
